# Generated by Django 5.0.6 on 2024-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='topic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'topic_name')},
        ),
    ]
